Repository chatty-potato/1take.web, pull requests merged in 2024-09, with the labels that each got.

#7 Docs/#6
  .github/ISSUE_TEMPLATE/issue_templte.md
  .github/PULL_REQUEST_TEMPLATE.md
  yarn.lock
Labels: Docs

#12 feat(test): add vitest for project
  .gitignore
  apps/admin/package.json
  apps/admin/tsconfig.app.json
  apps/admin/vitest.config.ts
  apps/web/package.json
  apps/web/src/App.test.tsx
  apps/web/tsconfig.app.json
  apps/web/vite.config.ts
  apps/web/vitest.config.ts
  apps/web/vitest.setup.ts
  libs/apis/package.json
  libs/apis/src/auth.test.ts
  libs/apis/src/fetcher.ts
  libs/apis/tsconfig.json
  package.json
  ui/package.json
  ui/src/Template/Template.spec.tsx
  ui/src/Template/Template.test.tsx
  ui/src/Template/Template.tsx
  ui/src/Template2/Button.tsx
  ui/tsconfig.app.json
  ui/vite.config.ts
  ui/vitest.config.ts
  ui/vitest.setup.ts
  vitest.workspace.ts
  yarn.lock
Labels: Feature, Setup

#19 SETUP(*): Typescript환경구축
  apps/admin/tsconfig.json
  apps/web/tsconfig.json
  libs/apis/tsconfig.json
  tsconfig.base.json
  ui/tsconfig.json
Labels: Setup

#24 [Fix]: @1take/apis lint 적용 및 api 경로 수정 #20
  eslint.config.js
  libs/apis/src/auth.test.ts
  libs/apis/src/auth.ts
  libs/apis/src/bookmark.ts
  libs/apis/src/interview.ts
  libs/apis/src/profile.ts
  libs/apis/src/qna.ts
  libs/apis/src/types/auth.type.ts
  libs/apis/src/types/bookmark.types.ts
  libs/apis/src/types/interview.types.ts
  libs/apis/src/types/profile.type.ts
  libs/apis/src/utils/config.ts
Labels: Feature, Fix
